apiVersion: apps/v1
kind: Deployment
metadata:
  name: revhire-user
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revhire-user
  template:
    metadata:
      labels:
        app : revhire-user
    spec:
      containers:
        - name: revhire-user
          image: saruku.azurecr.io/vamsimalleuserservices
          env:
          - name : DB_URL
            valueFrom: 
              secretKeyRef:
                name: db-credentials
                key: DB_URL
          - name : DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key : DB_USERNAME
          - name : DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_PASSWORD
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_PORT
