apiVersion : apps/v1
kind: Deployment
metadata:
  name: userservice 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice 
    spec:
      containers:
        - name: userservice 
          image: saruku.azurecr.io/userservice
          ports:
          - containerPort: 8081